theme: minima
title: Codes
author: Epic_Fenix
email: epix.warrior.empire@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I have researched and descifrated these codes from books and TV series I like  without help, based on 
  some fragments I found in the books. This is the guide for them who have just beggined their journey 
  to secret codes.


# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  EpcFnx # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
